version: "2"
services:
  db:
    build:
      context: .
      dockerfile: ./mysql.dockerfile
    ports:
      - 3306:3306

  node_app:
    build:
      context: .
      dockerfile: node.dockerfile
    depends_on:
       - db
    links:
      - db:mysql
    ports:
      - 3000:3000

networks:
  backend:
  frontend:
